import Config

# Show debug info in the branded 500 error page when it renders (in dev,
# Plug.Debugger usually catches first; this controls the fallback case).
config :ezagent_web, :show_error_debug, true

# task #87 — in dev, email goes to the in-memory Local adapter (preview at
# /dev/mailbox if mounted) so confirmation/reset links work with no SMTP.
# Prod uses the compile-pinned SMTP adapter (config.exs) + runtime smtp_config.
config :ezagent_web, EzagentWeb.Mailer, adapter: Swoosh.Adapters.Local

config :ezagent_core, EzagentCore.Repo,
  username: System.get_env("POSTGRES_USER", "ezagent_pg_compat"),
  password: System.get_env("POSTGRES_PASSWORD", "ezagent_pg_compat"),
  hostname: System.get_env("POSTGRES_HOST", "127.0.0.1"),
  port: String.to_integer(System.get_env("POSTGRES_PORT", "55432")),
  database: System.get_env("POSTGRES_DB", "ezagent_pg_compat_dev"),
  priv: "priv/repo_pg",
  pool_size: 5,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :ezagent_web, EzagentWeb.Endpoint,
  # Bound to 0.0.0.0 so the dev server is reachable over the tailnet — Allen
  # accesses esr-ng from a tailnet IP (100.x.x.x), not localhost (P0-D8).
  # `check_origin: false` below is required for the same reason: a LiveView WS
  # connection from a 100.x origin would otherwise be rejected. dev-only.
  http: [ip: {0, 0, 0, 0}, port: String.to_integer(System.get_env("PORT") || "10042")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "LB/r5X+0G50lTmGaZonOO8PxwMhtOxdS3J308T7s+w3fBI0R8fkZbABhqZxjOFqO",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:ezagent_web, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:ezagent_web, ~w(--watch)]},
    # 直接跑 vite(不经 `npm run dev`)。`npm run dev` 会派生 npm→sh→node(vite) 三层进程树;
    # BEAM 关闭时 Phoenix.Endpoint.Watcher 只 SIGTERM 到直接子进程 npm,孙子 vite 漏杀、被
    # reparent 到 init 成孤儿、继续占 5173,下次启动 watcher 的 vite 撞端口 → :watcher_command_error。
    # node 直跑 vite = 单进程、BEAM 直接管,关闭即清,根治孤儿占端口。
    node: [
      "node_modules/.bin/vite",
      "--host",
      "0.0.0.0",
      "--port",
      System.get_env("WORLD_VITE_PORT") || "5173",
      cd: Path.expand("../apps/ezagent_plugin_world/assets", __DIR__)
    ]
  ]

config :ezagent_plugin_world,
  world_module_url:
    "http://localhost:#{System.get_env("WORLD_VITE_PORT") || "5173"}/src/main.tsx",
  world_css_url: nil

# Resource-unification P2 — upload download-token signing secret (core-owned
# config key). Wired to the same value as the web endpoint's secret_key_base so
# tokens minted by web/operator surfaces verify identically.
config :ezagent_core, Ezagent.Uploads.DownloadToken,
  secret_key_base: "LB/r5X+0G50lTmGaZonOO8PxwMhtOxdS3J308T7s+w3fBI0R8fkZbABhqZxjOFqO"

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :ezagent_web, EzagentWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/ezagent_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :ezagent_web, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# task #87 — localhost dev: no cookie domain so the session cookie binds to
# the request host (prod sets it to ".ezagent.chat" via the endpoint default).
config :ezagent_web, :session_cookie_domain, nil
